title: Project
pages:
  hide: true
  template: altgallery
files: true
  sortable: true
  fields:
    caption:
      type: markdown
      label: Image Caption
      tools:
        - bold
        - italic
fields:
  title:
    label: Project Title
    type:  text
    width: 3/4
  year:
    label: Year
    type: number
    width: 1/4
  thumbnails:
    label: Main Thumbnails
    type: selector
    mode: multiple
    help: Prioritize these images to be shown as thumbnails on the homepage or index view
    size: 5
    types:
      - image
  # materials:
  #   label: Materials / Context
  #   type: markdown
  #   tools:
  #     - bold
  #     - italic
  #     - unorderedList
  #     - orderedList
  #     - link
  description:
    label: Project Description (en)
    type: markdown
    help: to make a line break without space, leave two empty spaces at the end of a line
    tools:
      - bold
      - italic
      - unorderedList
      - orderedList
      - link
  esdescription:
    label: Project Description (es)
    type: markdown
    help: to make a line break without space, leave two empty spaces at the end of a line
    tools:
      - bold
      - italic
      - unorderedList
      - orderedList
      - link
  mainGalleryTitle:
    type: text
    label: Main Gallery Title
    required: true
    default: Project Images
    help: the button text that will take viewers back to the main gallery
  childrenList:
    type: subpagelist
    label: Alt Gallery
