title: Project
pages:
  max: 1
  hide: true
  template: altgallery
files: true
  fields:
    caption:
      type: markdown
      label: Image Caption
      tools:
        - bold
        - italic
fields:
  title:
    label: Project Title
    type:  text
    width: 3/4
  year:
    label: Year
    type: number
    width: 1/4
  materials:
    label: Materials / Context
    type: markdown
    tools:
      - bold
      - italic
      - unorderedList
      - orderedList
      - link
  description:
    label: Project Description
    type: markdown
    tools:
      - bold
      - italic
      - unorderedList
      - orderedList
      - link
  childrenList:
    type: subpagelist
    label: Alt Gallery
  mainGalleryTitle:
    type: text
    label: Main Gallery Title
    required: true
    default: Project Images
    help: the button text that will take viewers back to the main gallery
